title: Locas - Open Source AI Location Orchestrator
description: "Make smarter decisions with our community-driven platform that orchestrates multiple AI services for powerful location analysis."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://locas.dev" # the base hostname & protocol for your site
github_username: azharlabs
github_repo: locas

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
sass:
  style: compressed

# Collection settings
collections:
  authors:
    output: true
    permalink: /authors/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "team"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag